# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bfad2272c6775e96346ba559e5e311be552faa33d92272c59ac75718d40415edccb35536167c138f02e440c776c436ebdd8d0973e458db80da2e682c69c5a52

test:
  secret_key_base: 5d28bf5147c4ff611a1b683312b74904247ffd6ff569ca875d1836b1ddf7bf68f6bc6b8af5eb7f61147ca906efdde2482bca3fa4815b8673c8a356a2cac23554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
